# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21ae2dd8490ef5553bebbb0230c39f56c5d9cda479d5d5237deb45cb12b202d36c8889e6e22d12cd258c023d6eb39cb4fe8e981c12d5d8d84a15ab1b03f00883

test:
  secret_key_base: eebd30709f5c6d5784e188f54196e24ed50e6e2459c81fc127fb1802e6fc05d3962632876513474ad5b184be214ceea84a9b94995cd5869c5ce96e163237aefd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
